# Generated by Django 2.1.4 on 2019-01-26 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.BooleanField(default=True)),
                ('status', models.BooleanField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'booking_room',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Room'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookingroom',
            unique_together={('room', 'date', 'start_time')},
        ),
    ]
