# Generated by Django 2.1.4 on 2019-01-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20190128_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
